### ISSUE TITLE
This plugin doesn't support git worktrees

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt-git#110]
As the underlying JGit doesn't support this.

https://git-scm.com/docs/git-worktree

**Comment by DavidPerezIngeniero** [comment]
Workaround: http://stackoverflow.com/questions/35699543/how-to-load-dynamically-a-sbt-plugin

**Comment by dwijnand** [comment]
Upstream JGit issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

**Comment by aij** [comment]
The README makes it sounds like using JGit is optional

> ### Using JGit ###
>
> If you do not have git installed and available on your path (e.g. you use windows), make sure your `git.sbt` or `~/.sbt/0.13/git.sbt` file looks like this:
> 
>     useJGit

but the plugin seems to be trying to use JGit even without that setting.

From the main working tree, I can even successfully run `git worktree list` within SBT. From a linked working tree, I get this error during SBT startup:

```
[error] org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
[error]         at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1379)
[error]         at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:115)
[error]         at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:97)
[error]         at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:139)
[error]         at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:88)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20(SbtGit.scala:121)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20$adapted(SbtGit.scala:121)
[error]         at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:39)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$19(SbtGit.scala:121)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$19$adapted(SbtGit.scala:121)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

I don't need JGit support since everyone here has `git` installed, but we do use worktrees quite a bit.

@DavidPerezIngeniero Disabling the plugin doesn't seem like much of a workaround... Won't that just break any configuration that uses the plugin when in a worktree?
