### ISSUE TITLE
0.9.3 fails with NPE.

### ISSUE THREAD

**Issue by hedefalk** [sbt/sbt-git#131]
```
[info] Resolved XXXX dependencies
java.lang.NullPointerException
	at org.slf4j.impl.AbstractSbtLoggerAdapter.debug(AbstractSbtLoggerAdapter.scala:38)
	at org.eclipse.jgit.util.FS.readPipe(FS.java:492)
	at org.eclipse.jgit.util.FS.readPipe(FS.java:464)
	at org.eclipse.jgit.util.FS.discoverGitSystemConfig(FS.java:613)
	at org.eclipse.jgit.util.FS.getGitSystemConfig(FS.java:653)
	at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemReader.java:97)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:176)
	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
	at com.typesafe.sbt.git.JGit$.apply(JGit.scala:118)
	at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:35)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$1.apply(SbtGit.scala:112)
	at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$1.apply(SbtGit.scala:112)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NullPointerException
[error] Use 'last' for the full log.
```

**Comment by leonardehrenfried** [comment]
And 0.9.2 works?

**Comment by hedefalk** [comment]
Sorry. I went straight from 0.8.3 which has worked for long. Was just cleaning up my ~/.sbt files. Let me check where it broke for me and come back…

**Comment by hedefalk** [comment]
No, 0.9.2 broken too. As I said, I went from 0.8.3 to 0.9.3 and on 0.9.3 I get this NPE always on one of my projects.

Downgrading to 0.9.2 didn't help. I will do the "bisect" now:

0.9.1 - broken
0.8.4 - works
0.9.0 - broken
0.8.5 - works.

**Comment by hedefalk** [comment]
Oh, more info:

It's definitely some classpath clashing with loggers going on:

On 0.9.0, I didn't get the same NPE, but:

```
java.lang.NoSuchFieldError: sbtLogger
	at sbtfrontend.FrontendPlugin$autoImport$$anonfun$frontendSettings$24$$anonfun$1.apply(FrontendPlugin.scala:112)
	at sbtfrontend.FrontendPlugin$autoImport$$anonfun$frontendSettings$24$$anonfun$1.apply(FrontendPlugin.scala:111)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at sbt.Project$.setProject(Project.scala:341)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:507)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchFieldError: sbtLogger
```

from the RevolverPlugin. It's "io.spray" % "sbt-revolver" % "0.8.0".

**Comment by hedefalk** [comment]
So, more info:

It's something with sl4fj clashes. On 0.9.0, I actually did get another error from a frontend plugin I'm using:

```
java.lang.NoSuchFieldError: sbtLogger
	at sbtfrontend.FrontendPlugin$autoImport$$anonfun$frontendSettings$24$$anonfun$1.apply(FrontendPlugin.scala:112)
	at sbtfrontend.FrontendPlugin$autoImport$$anonfun$frontendSettings$24$$anonfun$1.apply(FrontendPlugin.scala:111)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:97)
	at spray.revolver.RevolverPlugin$$anonfun$settings$12$$anonfun$apply$5.apply(RevolverPlugin.scala:94)
	at sbt.Project$.setProject(Project.scala:341)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:507)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchFieldError: sbtLogger
```

This line:
https://github.com/eltimn/sbt-frontend/blob/8d6a3db91869717339db571e17a5af3e75ec97e9/src/main/scala/sbtfrontend/FrontendPlugin.scala#L112

Seems like a race condition on what version of sl4jf between this plugin and jgit?

**Comment by bchazalet** [comment]
oh this doesn't look good...

**Comment by rmalleman** [comment]
I get this same problem.  Weird enough I can only reproduce on my ci server(drone), it works locally just fine.
