### ISSUE TITLE
No longer possible to add plugin without having git installed

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-git#145]
We have a custom release plugin that depends on sbt-git for getting the `gitCurrentBranch`
Today we migrated to sbt 1.0.x and sbt-git 9.3.0 but our CI builds suddenly start to fail with below error

On `0.8.5` there was no need to have git installed in the build environment
The specific code that introduced this bug is https://github.com/sbt/sbt-git/blob/dac37c08b7076dd308dbfa53ba264b3118c5b913/src/main/scala/com/typesafe/sbt/SbtGit.scala#L123
The rest of the code sticks to eclipse.jgit for performing git actions

```
java.io.IOException: Cannot run program "git": error=2, No such file or directory
...
Caused by: java.io.IOException: error=2, No such file or directory
[error] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[error] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
[error] 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[error] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:111)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:202)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error] 	at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:138)
[error] 	at com.typesafe.sbt.SbtGit$$$Lambda$5070/1260621417.apply(Unknown Source)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
```

this is related to #141

**Comment by MansurAshraf** [comment]
I am running into the same issue, is there a work around for this since I am assuming fix won't be available till the next release?
