### ISSUE TITLE
No version after 1.0.0 works

### ISSUE THREAD

**Issue by mjcramer** [sbt/sbt-git#231]
I can't even get sbt to load when using the sbt-git plugin version > 1.0.0. I create a new project using 
```
sbt new scala/scala-seed.g8
```

Then, in my new project I create a new file, `project/plugins.sbt` with the following contents:
```
addSbtPlugin("com.github.sbt" % "sbt-git" % "2.0.0")
```
Then, when I try to load sbt, I get the following error:
```
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'gitReader' (com.github.sbt.git.ReadableGit, com.typesafe.sbt.git.ReadableGit), 'gitRunner' (sbt.Task[com.github.sbt.git.GitRunner], sbt.Task[com.typesafe.sbt.git.GitRunner])
	at scala.sys.package$.error(package.scala:30)
	at sbt.internal.Index$.stringToKeyMap0(EvaluateConfigurations.scala:375)
	at sbt.internal.Index$.stringToKeyMap(EvaluateConfigurations.scala:359)
	at sbt.internal.Load$.structureIndex(Load.scala:332)
	at sbt.internal.Load$.$anonfun$apply$8(Load.scala:266)
	at sbt.internal.Load$.timed(Load.scala:1406)
	at sbt.internal.Load$.apply(Load.scala:266)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:961)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:961)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:914)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:223)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:577)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:567)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:567)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Some keys were defined with the same name but different types: 'gitReader' (com.github.sbt.git.ReadableGit, com.typesafe.sbt.git.ReadableGit), 'gitRunner' (sbt.Task[com.github.sbt.git.GitRunner], sbt.Task[com.typesafe.sbt.git.GitRunner])
```
I've tried clearing out my caches, everything in `~/.ivy2/caches` and `/User/cramer/Library/Caches/Coursier`. 

Has anyone had any success loading this?

**Comment by armanbilge** [comment]
Do you have any global sbt plugins?
https://www.scala-sbt.org/1.x/docs/Using-Plugins.html

**Comment by mjcramer** [comment]
Ack! 🤦 

Nailed it. I totally forgot about global plugins. I was using one (https://github.com/agemooij/sbt-prompt) that apparently hadn't been updated in a while. Thank you so much. That has been driving me crazy for a week!
